In [2]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

%matplotlib inline

In [3]:
df = pd.read_csv('/Users/Excellus/Downloads/carprice.csv')

In [4]:
df.head(10)

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   
2  BMW    1 Series  2011  premium unleaded (required)      300.0   
3  BMW    1 Series  2011  premium unleaded (required)      230.0   
4  BMW    1 Series  2011  premium unleaded (required)      230.0   
5  BMW    1 Series  2012  premium unleaded (required)      230.0   
6  BMW    1 Series  2012  premium unleaded (required)      300.0   
7  BMW    1 Series  2012  premium unleaded (required)      300.0   
8  BMW    1 Series  2012  premium unleaded (required)      230.0   
9  BMW    1 Series  2013  premium unleaded (required)      230.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   
2               6.0            MANUAL  rear wheel drive              2.0   
3               6.0            MANUAL  rear wheel drive              2.0   
4               6.0            MANUAL  rear wheel drive              2.0   
5               6.0            MANUAL  rear wheel drive              2.0   
6               6.0            MANUAL  rear wheel drive              2.0   
7               6.0            MANUAL  rear wheel drive              2.0   
8               6.0            MANUAL  rear wheel drive              2.0   
9               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   
2                Luxury,High-Performance      Compact         Coupe   
3                     Luxury,Performance      Compact         Coupe   
4                                 Luxury      Compact   Convertible   
5                     Luxury,Performance      Compact         Coupe   
6                     Luxury,Performance      Compact   Convertible   
7                Luxury,High-Performance      Compact         Coupe   
8                                 Luxury      Compact   Convertible   
9                                 Luxury      Compact   Convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650  
2           28        20        3916  36350  
3           28        18        3916  29450  
4           28        18        3916  34500  
5           28        18        3916  31200  
6           26        17        3916  44100  
7           28        20        3916  39300  
8           28        18        3916  36900  
9           27        18        3916  37200

In [5]:
df.describe()

Year    Engine HP  Engine Cylinders  Number of Doors  \
count  11914.000000  11845.00000      11884.000000     11908.000000   
mean    2010.384338    249.38607          5.628829         3.436093   
std        7.579740    109.19187          1.780559         0.881315   
min     1990.000000     55.00000          0.000000         2.000000   
25%     2007.000000    170.00000          4.000000         2.000000   
50%     2015.000000    227.00000          6.000000         4.000000   
75%     2016.000000    300.00000          6.000000         4.000000   
max     2017.000000   1001.00000         16.000000         4.000000   

        highway MPG      city mpg    Popularity          MSRP  
count  11914.000000  11914.000000  11914.000000  1.191400e+04  
mean      26.637485     19.733255   1554.911197  4.059474e+04  
std        8.863001      8.987798   1441.855347  6.010910e+04  
min       12.000000      7.000000      2.000000  2.000000e+03  
25%       22.000000     16.000000    549.000000  2.100000e+04  
50%       26.000000     18.000000   1385.000000  2.999500e+04  
75%       30.000000     22.000000   2009.000000  4.223125e+04  
max      354.000000    137.000000   5657.000000  2.065902e+06

In [6]:
selectedc = [
    'Make',
    'Model',
    'Year',
    'Engine HP',
    'Engine Cylinders',
    'Transmission Type',
    'Vehicle Style',
    'highway MPG',
    'city mpg',
    'MSRP'
]

In [7]:
df.columns

Index(['Make', 'Model', 'Year', 'Engine Fuel Type', 'Engine HP',
       'Engine Cylinders', 'Transmission Type', 'Driven_Wheels',
       'Number of Doors', 'Market Category', 'Vehicle Size', 'Vehicle Style',
       'highway MPG', 'city mpg', 'Popularity', 'MSRP'],
      dtype='object')

In [8]:
dfn = df[selectedc]

In [9]:
dfn.head()

Make       Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0  BMW  1 Series M  2011      335.0               6.0            MANUAL   
1  BMW    1 Series  2011      300.0               6.0            MANUAL   
2  BMW    1 Series  2011      300.0               6.0            MANUAL   
3  BMW    1 Series  2011      230.0               6.0            MANUAL   
4  BMW    1 Series  2011      230.0               6.0            MANUAL   

  Vehicle Style  highway MPG  city mpg   MSRP  
0         Coupe           26        19  46135  
1   Convertible           28        19  40650  
2         Coupe           28        20  36350  
3         Coupe           28        18  29450  
4   Convertible           28        18  34500

In [10]:
dfn.columns = dfn.columns.str.replace(' ', '_').str.lower()

In [11]:
dfn.columns

Index(['make', 'model', 'year', 'engine_hp', 'engine_cylinders',
       'transmission_type', 'vehicle_style', 'highway_mpg', 'city_mpg',
       'msrp'],
      dtype='object')

In [12]:
dfn.rename(columns={'msrp': 'price'}, inplace=True)

C:\Users\Excellus\AppData\Local\Temp\ipykernel_1152\3320719001.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfn.rename(columns={'msrp': 'price'}, inplace=True)


In [13]:
dfn.isnull().sum()

make                  0
model                 0
year                  0
engine_hp            69
engine_cylinders     30
transmission_type     0
vehicle_style         0
highway_mpg           0
city_mpg              0
price                 0
dtype: int64

In [14]:
dfn.fillna(0,inplace=True)

C:\Users\Excellus\AppData\Local\Temp\ipykernel_1152\3365192939.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfn.fillna(0,inplace=True)


In [15]:
dfn.isnull().sum()

make                 0
model                0
year                 0
engine_hp            0
engine_cylinders     0
transmission_type    0
vehicle_style        0
highway_mpg          0
city_mpg             0
price                0
dtype: int64

In [16]:
dfn['transmission_type'].value_counts()

AUTOMATIC           8266
MANUAL              2935
AUTOMATED_MANUAL     626
DIRECT_DRIVE          68
UNKNOWN               19
Name: transmission_type, dtype: int64

In [17]:
dfcorr = dfn[['highway_mpg', 'city_mpg', 'engine_cylinders', 'engine_hp', 'year']].corr()
dfcorr

highway_mpg  city_mpg  engine_cylinders  engine_hp      year
highway_mpg          1.000000  0.886829         -0.614541  -0.415707  0.258240
city_mpg             0.886829  1.000000         -0.587306  -0.424918  0.198171
engine_cylinders    -0.614541 -0.587306          1.000000   0.774851 -0.040708
engine_hp           -0.415707 -0.424918          0.774851   1.000000  0.338714
year                 0.258240  0.198171         -0.040708   0.338714  1.000000

In [18]:
dfn.columns

Index(['make', 'model', 'year', 'engine_hp', 'engine_cylinders',
       'transmission_type', 'vehicle_style', 'highway_mpg', 'city_mpg',
       'price'],
      dtype='object')

In [19]:
mean_price = dfn['price'].mean()
dfn['above_average'] = (dfn['price'] > mean_price).astype(int)

C:\Users\Excellus\AppData\Local\Temp\ipykernel_1152\1647951904.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfn['above_average'] = (dfn['price'] > mean_price).astype(int)


In [20]:
dfn['above_average'] = dfn['above_average'].astype(int)
dfn['above_average']

C:\Users\Excellus\AppData\Local\Temp\ipykernel_1152\3716195582.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfn['above_average'] = dfn['above_average'].astype(int)


0        1
1        1
2        0
3        0
4        0
        ..
11909    1
11910    1
11911    1
11912    1
11913    0
Name: above_average, Length: 11914, dtype: int32

In [21]:
from sklearn.model_selection import train_test_split

In [22]:
df_full_train, df_test = train_test_split(dfn, test_size=0.2, random_state=42)

In [23]:
df_train, df_val = train_test_split(df_full_train, test_size=0.25, random_state=42)

In [24]:
len(df_train), len(df_test), len(df_val)

(7148, 2383, 2383)

In [25]:
df_train = df_train.reset_index(drop=True)
df_test = df_test.reset_index(drop=True)
df_val = df_val.reset_index(drop=True)
df_train.head()

make     model  year  engine_hp  engine_cylinders transmission_type  \
0   Mitsubishi  Endeavor  2011      225.0               6.0         AUTOMATIC   
1          Kia   Borrego  2009      276.0               6.0         AUTOMATIC   
2  Lamborghini  Gallardo  2012      570.0              10.0            MANUAL   
3    Chevrolet  Colorado  2016      200.0               4.0         AUTOMATIC   
4      Pontiac      Vibe  2009      158.0               4.0         AUTOMATIC   

     vehicle_style  highway_mpg  city_mpg   price  above_average  
0          4dr SUV           19        15   33599              0  
1          4dr SUV           21        17   26245              0  
2      Convertible           20        12  248000              1  
3  Crew Cab Pickup           27        20   24990              0  
4    4dr Hatchback           26        20   20475              0

In [26]:
y_train = df_train['above_average']
del df_train['above_average']
y_test = df_test['above_average']
del df_test['above_average']
y_val = df_val['above_average']
del df_val['above_average']

In [27]:
dfn.dtypes

make                  object
model                 object
year                   int64
engine_hp            float64
engine_cylinders     float64
transmission_type     object
vehicle_style         object
highway_mpg            int64
city_mpg               int64
price                  int64
above_average          int32
dtype: object

In [28]:
categorical = ['make', 'model', 'transmission_type', 'vehicle_style']

In [29]:
from sklearn.metrics import mutual_info_score

In [30]:
def mutual_info_average(series):
    return mutual_info_score(series, df_full_train['above_average'])

In [31]:
df_full_train[categorical].apply(mutual_info_average)

make                 0.238724
model                0.460994
transmission_type    0.020884
vehicle_style        0.083390
dtype: float64

In [32]:
from sklearn.feature_extraction import DictVectorizer

In [33]:
dv = DictVectorizer(sparse=False) 

In [34]:
train_dict = df_train.to_dict(orient= 'records')
train_dict

[{'make': 'Mitsubishi',
  'model': 'Endeavor',
  'year': 2011,
  'engine_hp': 225.0,
  'engine_cylinders': 6.0,
  'transmission_type': 'AUTOMATIC',
  'vehicle_style': '4dr SUV',
  'highway_mpg': 19,
  'city_mpg': 15,
  'price': 33599},
 {'make': 'Kia',
  'model': 'Borrego',
  'year': 2009,
  'engine_hp': 276.0,
  'engine_cylinders': 6.0,
  'transmission_type': 'AUTOMATIC',
  'vehicle_style': '4dr SUV',
  'highway_mpg': 21,
  'city_mpg': 17,
  'price': 26245},
 {'make': 'Lamborghini',
  'model': 'Gallardo',
  'year': 2012,
  'engine_hp': 570.0,
  'engine_cylinders': 10.0,
  'transmission_type': 'MANUAL',
  'vehicle_style': 'Convertible',
  'highway_mpg': 20,
  'city_mpg': 12,
  'price': 248000},
 {'make': 'Chevrolet',
  'model': 'Colorado',
  'year': 2016,
  'engine_hp': 200.0,
  'engine_cylinders': 4.0,
  'transmission_type': 'AUTOMATIC',
  'vehicle_style': 'Crew Cab Pickup',
  'highway_mpg': 27,
  'city_mpg': 20,
  'price': 24990},
 {'make': 'Pontiac',
  'model': 'Vibe',
  'year': 200

In [36]:
X_train = dv.fit_transform(train_dict)
X_train

array([[1.500e+01, 6.000e+00, 2.250e+02, ..., 0.000e+00, 0.000e+00,
        2.011e+03],
       [1.700e+01, 6.000e+00, 2.760e+02, ..., 0.000e+00, 0.000e+00,
        2.009e+03],
       [1.200e+01, 1.000e+01, 5.700e+02, ..., 0.000e+00, 0.000e+00,
        2.012e+03],
       ...,
       [1.700e+01, 6.000e+00, 2.600e+02, ..., 0.000e+00, 0.000e+00,
        2.012e+03],
       [1.900e+01, 4.000e+00, 1.360e+02, ..., 0.000e+00, 0.000e+00,
        1.993e+03],
       [1.700e+01, 6.000e+00, 3.650e+02, ..., 1.000e+00, 0.000e+00,
        2.015e+03]])

In [37]:
val_dict = df_val.to_dict(orient= 'records')
X_val = dv.transform(val_dict)
test_dict = df_test.to_dict(orient= 'records')
X_test = dv.transform(test_dict)

In [38]:
X_test

array([[1.300e+01, 6.000e+00, 2.750e+02, ..., 0.000e+00, 0.000e+00,
        2.005e+03],
       [2.500e+01, 4.000e+00, 1.700e+02, ..., 1.000e+00, 0.000e+00,
        2.016e+03],
       [1.900e+01, 6.000e+00, 2.480e+02, ..., 0.000e+00, 0.000e+00,
        2.016e+03],
       ...,
       [2.400e+01, 4.000e+00, 1.500e+02, ..., 1.000e+00, 0.000e+00,
        2.015e+03],
       [2.300e+01, 5.000e+00, 1.700e+02, ..., 0.000e+00, 1.000e+00,
        2.014e+03],
       [2.400e+01, 6.000e+00, 2.550e+02, ..., 0.000e+00, 0.000e+00,
        2.015e+03]])

In [39]:
from sklearn.linear_model import LogisticRegression

In [40]:
model = LogisticRegression(solver='liblinear', C=10, max_iter=1000, random_state=42)

In [41]:
model.fit(X_train, y_train)

LogisticRegression(C=10, max_iter=1000, random_state=42, solver='liblinear')

In [42]:
model.intercept_[0]

-9.658766624208182e-05

In [43]:
model.coef_[0]

array([-4.11929852e-03, -7.70422528e-04, -2.34840078e-03, -3.65829166e-03,
       -4.36374719e-04,  8.17137188e-09,  5.67310553e-09, -5.68823880e-06,
        2.77909911e-04,  2.70534500e-09, -3.14938692e-10,  2.79201788e-05,
       -9.77845187e-05, -1.95218229e-04,  1.49215080e-04, -1.03549690e-04,
       -4.88850074e-08,  2.18875832e-09,  1.35618983e-04,  2.90223708e-04,
        1.12189903e-05, -5.71867022e-06, -1.01015411e-05,  1.15234778e-05,
       -3.75067171e-05, -1.58301636e-04,  1.76431047e-09,  4.92020025e-05,
       -1.76676171e-04,  1.31665603e-06,  3.74616179e-08,  7.89761481e-09,
        2.73301839e-10,  1.45306541e-06,  1.51128889e-10,  4.67039667e-05,
       -9.62089944e-07,  4.67932944e-04, -4.83995323e-07,  4.57113433e-08,
       -4.31153439e-07,  7.18548030e-08,  1.00003017e-09, -2.89431845e-04,
       -3.82885844e-08,  2.18399485e-10, -5.14585175e-05, -2.19680573e-07,
        4.19821986e-09,  3.42522758e-04, -4.26245834e-05, -2.96919173e-04,
        1.35107760e-04, -

In [44]:
preed = model.predict(X_train)

In [45]:
probX = model.predict_proba(X_train)

In [46]:
probX[:, 1]

array([4.76022446e-028, 4.44560929e-057, 1.00000000e+000, ...,
       5.52372340e-049, 1.03847986e-151, 2.61906782e-002])

In [47]:
predv = model.predict(X_val)
(predv == y_val).mean()

0.9995803608896349

In [48]:
featuree= [
    'year',
'engine_hp',
'transmission_type',
'city_mpg'
]

In [49]:
scores = {}
for feature in featuree:
    df_trainf = df_train.drop(columns=[feature])
    df_testf = df_test.drop(columns=[feature])
    df_valf = df_val.drop(columns=[feature])
    
    trainf_dict = df_trainf.to_dict(orient= 'records')
    X_trainf = dv.fit_transform(trainf_dict)
    val_dictf = df_valf.to_dict(orient= 'records')
    X_valf = dv.transform(val_dictf)
    test_dictf = df_testf.to_dict(orient= 'records')
    X_testf = dv.transform(test_dictf)
    
    model.fit(X_trainf, y_train)
    preedf = model.predict(X_valf)
    
    scores[feature] = (preedf == y_val).mean()
print(scores)

{'year': 0.9471254720939991, 'engine_hp': 1.0, 'transmission_type': 0.9995803608896349, 'city_mpg': 0.9995803608896349}


In [91]:
df_val.year

AttributeError: 'DataFrame' object has no attribute 'year'