In [1]:
import numpy as np
import pandas as pd

In [2]:
pd.__version__

'2.2.2'

### Downloading dataset

In [6]:
!wget https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv

--2024-09-23 08:43:21--  https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv
Loaded CA certificate '/usr/ssl/certs/ca-bundle.crt'
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 298573 (292K) [text/plain]
Saving to: 'laptops.csv'

     0K .......... .......... .......... .......... .......... 17%  387K 1s
    50K .......... .......... .......... .......... .......... 34% 1.23M 0s
   100K .......... .......... .......... .......... .......... 51%  632K 0s
   150K .......... .......... .......... .......... .......... 68% 1.05M 0s
   200K .......... .......... .......... .......... .......... 85%  951K 0s
   250K .......... .......... .......... .......... .         100% 1.00M=0.4s

2024-09-23 08:43:22 (752 KB/s) - 'laptops.csv' saved 

In [8]:
df = pd.read_csv('laptops.csv')

In [9]:
df

Laptop       Status   Brand  \
0     ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...          New    Asus   
1     Alurin Go Start Intel Celeron N4020/8GB/256GB ...          New  Alurin   
2     ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...          New    Asus   
3     MSI Katana GF66 12UC-082XES Intel Core i7-1270...          New     MSI   
4     HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...          New      HP   
...                                                 ...          ...     ...   
2155  Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...  Refurbished   Razer   
2156  Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...  Refurbished   Razer   
2157  Razer Blade 17 FHD 360Hz Intel Core i7-11800H/...  Refurbished   Razer   
2158  Razer Book 13 Intel Evo Core i7-1165G7/16GB/1T...  Refurbished   Razer   
2159  Razer Book FHD+ Intel Evo Core i7-1165G7/16GB/...  Refurbished   Razer   

           Model                CPU  RAM  Storage Storage type       GPU  \
0     ExpertBook      Intel Core i5    8      512          SSD       NaN   
1             Go      Intel Celeron    8      256          SSD       NaN   
2     ExpertBook      Intel Core i3    8      256          SSD       NaN   
3         Katana      Intel Core i7   16     1000          SSD  RTX 3050   
4            15S      Intel Core i5   16      512          SSD       NaN   
...          ...                ...  ...      ...          ...       ...   
2155       Blade      Intel Core i7   16     1000          SSD  RTX 3060   
2156       Blade      Intel Core i7   16     1000          SSD  RTX 3070   
2157       Blade      Intel Core i7   32     1000          SSD  RTX 3080   
2158        Book  Intel Evo Core i7   16     1000          SSD       NaN   
2159        Book  Intel Evo Core i7   16      256          SSD       NaN   

      Screen Touch  Final Price  
0       15.6    No      1009.00  
1       15.6    No       299.00  
2       15.6    No       789.00  
3       15.6    No      1199.00  
4       15.6    No       669.01  
...      ...   ...          ...  
2155    17.3    No      2699.99  
2156    17.3    No      2899.99  
2157    17.3    No      3399.99  
2158    13.4   Yes      1899.99  
2159    13.4   Yes      1699.99  

[2160 rows x 12 columns]

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2160 entries, 0 to 2159
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Laptop        2160 non-null   object 
 1   Status        2160 non-null   object 
 2   Brand         2160 non-null   object 
 3   Model         2160 non-null   object 
 4   CPU           2160 non-null   object 
 5   RAM           2160 non-null   int64  
 6   Storage       2160 non-null   int64  
 7   Storage type  2118 non-null   object 
 8   GPU           789 non-null    object 
 9   Screen        2156 non-null   float64
 10  Touch         2160 non-null   object 
 11  Final Price   2160 non-null   float64
dtypes: float64(2), int64(2), object(8)
memory usage: 202.6+ KB


In [11]:
df.isnull().sum()

Laptop             0
Status             0
Brand              0
Model              0
CPU                0
RAM                0
Storage            0
Storage type      42
GPU             1371
Screen             4
Touch              0
Final Price        0
dtype: int64

In [13]:
df.describe()

RAM      Storage       Screen  Final Price
count  2160.000000  2160.000000  2156.000000  2160.000000
mean     15.413889   596.294444    15.168112  1312.638509
std       9.867815   361.220506     1.203329   911.475417
min       4.000000     0.000000    10.100000   201.050000
25%       8.000000   256.000000    14.000000   661.082500
50%      16.000000   512.000000    15.600000  1031.945000
75%      16.000000  1000.000000    15.600000  1708.970000
max     128.000000  4000.000000    18.000000  7150.470000

In [12]:
df['Brand'].nunique()

27

In [14]:
df.groupby('ocean_proximity').median_house_value.mean().round(2)

ocean_proximity
<1H OCEAN     240084.29
INLAND        124805.39
ISLAND        380440.00
NEAR BAY      259212.31
NEAR OCEAN    249433.98
Name: median_house_value, dtype: float64

In [15]:
df.total_bedrooms.mean()

537.8705525375618

In [16]:
df['total_bedrooms'] = df.total_bedrooms.fillna(df.total_bedrooms.mean())

In [17]:
df.total_bedrooms.mean()

537.8705525375639

In [18]:
df.isnull().sum()

longitude             0
latitude              0
housing_median_age    0
total_rooms           0
total_bedrooms        0
population            0
households            0
median_income         0
median_house_value    0
ocean_proximity       0
dtype: int64

In [20]:
df_island = df[
    df['ocean_proximity']== 'ISLAND'
]

In [25]:
X = df_island[['housing_median_age', 'total_rooms', 'total_bedrooms']].values

In [26]:
X

array([[  27., 1675.,  521.],
       [  52., 2359.,  591.],
       [  52., 2127.,  512.],
       [  52.,  996.,  264.],
       [  29.,  716.,  214.]])

In [27]:
X_T = X.T

In [28]:
X_T

array([[  27.,   52.,   52.,   52.,   29.],
       [1675., 2359., 2127.,  996.,  716.],
       [ 521.,  591.,  512.,  264.,  214.]])

In [43]:
XTX = np.dot(X, X_T)

In [44]:
XTX

array([[3077795., 4260640., 3830881., 1807248., 1311577.],
       [4260640., 5916866., 5322889., 2508292., 1817026.],
       [3830881., 5322889., 4788977., 2256364., 1634008.],
       [1807248., 2508292., 2256364., 1064416.,  771140.],
       [1311577., 1817026., 1634008.,  771140.,  559293.]])

In [39]:
y = [950, 1300, 800, 1000, 1300]

In [40]:
invxx = np.linalg.inv(XTX)

In [45]:
invx = np.dot(invxx, X_T)

In [49]:
w = np.dot(invx, y)

In [50]:
w[-1]

5.6992294550655656